name: Convert Weibo AdBlock

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行
  workflow_dispatch:  # 允许手动触发

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run conversion script
      run: python convert.py

    - name: Check generated file
      run: |
        ls -l Weibo_AdBlock.sgmodule
        cat Weibo_AdBlock.sgmodule

    - name: Check for changes
      id: check_changes
      run: |
        git status --porcelain
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push if changed
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Weibo_AdBlock.sgmodule
        git commit -m "Auto convert Weibo AdBlock to Surge module"
        git push
