name: Convert Weibo AdBlock

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行
  workflow_dispatch:  # 允许手动触发

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run conversion script
      run: python convert.py
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Weibo_AdBlock.sgmodule
        git commit -m "Auto convert Weibo AdBlock to Surge module" -a
    - name: Push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Weibo_AdBlock.sgmodule
        git commit -m "Auto convert Weibo AdBlock to Surge module" -a || echo "No changes to commit"
        git push
